version: '3.9'

services:
  postgres:
    image: postgres
    shm_size: 50MB
    volumes:
      - .init_db/library.sql:/docker-entrypoint-initdb.d/library.sql
      - .pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=librarian
      - POSTGRES_PASSWORD=librarian
      - POSTGRES_DB=library
    expose:
      - 5432
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
  songs_library:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:8080"
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - .:/SongsLibrary
    environment:
      - appname="SongsLibrary"
      - appversion="1.0.0"
      - loglevel="debug"
      - port="8080"
      - host="0.0.0.0"
      - dsn="postgres://librarian:librarian@0.0.0.0:5432/library?sslmode=disable"