version: '3.9'

services:
  postgres:
    image: postgres
    shm_size: 50MB
    volumes:
      - .init_db/library.sql:/docker-entrypoint-initdb.d/library.sql
      - .pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=librarian
      - POSTGRES_PASSWORD=librarian
      - POSTGRES_DB=library
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - library-net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'

  songs_library:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "4000:8080"
    networks:
      - library-net
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - .:/SongsLibrary
    environment:
      - appname="SongsLibrary"
      - appversion="1.0.0"
      - loglevel="debug"
      - port="8080"
      - host="0.0.0.0"
      - dsn="postgres://librarian:librarian@postgres:5432/library?sslmode=disable"

networks:
  library-net:
    driver: bridge
    enable_ipv6: true
#    ipam:
#      config:
#        - subnet: 2401:da80:1000:2::/64
