version: '3.9'

services:
  postgres:
    image: postgres
    shm_size: 50MB
    volumes:
      - .init_db/library.sql:/docker-entrypoint-initdb.d/library.sql
      - .pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=librarian
      - POSTGRES_PASSWORD=librarian
      - POSTGRES_DB=library
    expose:
      - 5432
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'